### PR TITLE
Ccbuf dith4 mode svd patch

### LINKED ISSUE #377: Regression in behaviour of 4-bit dither register access for TCC on SAMD51J/G
I opened issue #88 with the original bug in the register access implementation. I've noticed this behavior has regressed in version 0.9.0 of the `atsamd51j` and `atsamd51g` PAC crates.

### PR DESCRIPTION
**Pull request by TDHolmes**
Closes #377

### CODE REVIEW

File: update.sh [hunk 1]
```diff
@@ -30,9 +30,15 @@ for xsl in svd/devices/*\.xsl; do
...
   rm lib.rs
+
+  # remove last characters, because they just represent the memory size
   ${SED} -i "s/${CHIP}/${CHIP:0:9}/g" src/lib.rs
+
   cargo +nightly fmt
   rustfmt +nightly build.rs
 
+  # ignore all clippy warnings/errors in auto-generated code
+  ${SED} -i "s/#\!\[no_std\]/#\!\[allow\(clippy::all\)\]\n#\!\[no_std\]/g" src/lib.rs
```
Comment (TDHolmes) [inline update.sh:41]: This is needed because previously, I had manually modified the `lib.rs`'s to add `#![allow(clippy::all)]`

**Comment by sajattack** [comment]
Thanks!
