### PR TITLE
samd51 UsbBus: Fix interrupts not enabling & missing poll events around USB reset

### LINKED ISSUE #105: atsamd usb serial not receiving characters until close
I have a usb commit in #104 here for pygamer When you open the port with `screen /dev/blah 115200` and type nothing is printed on screen and Ive checked and the characters arent even received. I thought it was maybe interrupts, but I implemented the polling to upper case echo example and it has the same behavior. 

So maybe my implementation is broken, but wait I noticed as you close screen, the led example will trigger and In the case of the polling to upper case example when you reopen screen you'll see your previous chars printed to screen.

So the act of closing is triggering for some reason. I can't confirm on itsy but I presume its the same. So maybe its my setup for some reason. I checked with [stm32-usb](https://github.com/stm32-rs/stm32-usbd) and a [upper case polling bluepill example](https://github.com/stm32-rs/stm32-usbd-examples/tree/master/example-stm32f103c8
) and can confirm those characters are echoed immediately using screen so its not my setup.

I have a feeling using the stty as given in directions in Itsy, opens and closes and is thus triggering a flush somehow and so this hasnt been noticed until now.

Im not yet familiar with the usb device implementation but I think it would lie in there somewhere. Any thoughts @sajattack ?

### PR DESCRIPTION
**Pull request by twitchyliquid64**
Fixes #105.
Co-authored-by: Jacob Rosenthal <jacobrosenthal@gmail.com>

So it looks like the issue came down to our writes to `EPINTENSET[n]` not sticking. I found one really important sentence:

> This [EPINTENSET] register is cleared by USB reset or when EPEN[n] is zero.

-- Page 1164 / 2129 of the SAM D5x/E5x Family Data Sheet

There is no register or other reference to `EPEN`. I've taken it to mean a non-zero value for `EPCFG[n].EPTYPE[0/1]`, but to be sure we configure the endpoint interrupts last.

The remaining changes are the result of an iterative audit of registers, ordering, and minimizing unnecessary writes so the driver is as reliable as possible.

### CODE REVIEW

**Comment by jacobrosenthal** [comment]
Man. Nice job. Confirm fix.
Not sure if you saw it but the zephyr implementation has something akin to this.  I tried a few implementations but never got it working
https://github.com/zephyrproject-rtos/zephyr/blob/master/drivers/usb/device/usb_dc_sam0.c#L98

**Comment by jacobrosenthal** [comment]
Wanna inspect these logs before we merge
https://gist.github.com/jacobrosenthal/cf4e909558c4f3ef4c03fa378d64e39e

This is upstream vs this patch, but with the WRITE FAIL debug line added to the transfer complete that has commented out


Shows some nice removals, but also shows were tending to now respond to the 'wrong' interrupts and getting a bunch of write fails we never used to

File: hal/src/samd51/usb/bus.rs [hunk 1]
```diff
@@ -326,10 +327,18 @@ impl<'a> Bank<'a, InBank> {
             desc.set_byte_count(0);
         }
 
-        self.epstatusclr(idx)
-            .write(|w| w.stallrq1().set_bit().dtglin().set_bit().bk1rdy().set_bit());
-        self.epintenset(idx).write(|w| w.trcpt1().set_bit());
-        self.clear_transfer_complete();
+        if idx == 0 {
```
Comment (jacobrosenthal) [inline hal/src/samd51/usb/bus.rs]: Is this scope necessary at all? From manual


        //The USB bus reset is initiated by a connected host and MANAGED BY HARDWARE.
        // During USB reset the following registers are cleared:
        // Device Endpoint Configuration (EPCFG) register - except for Endpoint 0
        // Device Frame Number (FNUM) register
        // Device Address (DADD) register
        // Device Endpoint Interrupt Enable Clear/Set (EPINTENCLR/SET) register
        // Device Endpoint Interrupt Flag (EPINTFLAG) register
        // Transmit Stall 0 bit in the Endpoint Status register (EPSTATUS.STALLRQ0)
        // Transmit Stall 1 bit in the Endpoint Status register (EPSTATUS.STALLRQ1)
        // Endpoint Interrupt Summary (EPINTSMRY) register

File: hal/src/samd51/usb/bus.rs [hunk 2]
```diff
@@ -441,15 +451,23 @@ impl<'a> Bank<'a, OutBank> {
...
-        self.epstatusclr(idx).write(|w| {
-            w.stallrq0()
-                .set_bit()
-                .dtglout()
-                .set_bit()
-                .bk0rdy()
-                .set_bit()
-        });
-        self.epintenset(idx)
+        if idx == 0 {
```
Comment (jacobrosenthal) [inline hal/src/samd51/usb/bus.rs]: Same

File: hal/src/samd51/usb/bus.rs (hunk 1 above)
Comment (twitchyliquid64) [reply hal/src/samd51/usb/bus.rs]: I think so, I put that conditional in so that we reset those bits on endpoint zero only, which is the endpoint which does not get cleared.

Comment (twitchyliquid64) [reply hal/src/samd51/usb/bus.rs]: Wait did I read that wrong? The EPSTATUS register is reset for all endpoints?

**Comment by jacobrosenthal** [comment]
LGTM

**Comment by sajattack** [comment]
Thanks guys.
